name: Auto-fix and Merge on Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  publish:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Substitute publish times
        run: |
          ./publish-articles.sh

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "3036+eltiare@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-fix after approval"
          git push
